export const TASK_RULE = 'TASK_RULE';
export const TASK_PROPER = 'TASK_PROPER';
export const TASK_TIMEOUT = 'TASK_TIMEOUT';
export const TYPE_TUTORIAL = 'TYPE_TUTORIAL';
export const TYPE_RANDOMISED = 'TYPE_RANDOMISED';
export const TYPE_NONRANDOMISED = 'TYPE_NONRANDOMISED';

export const TASK_FLOW = [
	TASK_RULE,
	TASK_PROPER
];

export const STIMULI_BIRD = 'STIMULI_BIRD';
export const STIMULI_SNAKE = 'STIMULI_SNAKE';

export const MODE_STIMULI = {
	[TYPE_TUTORIAL]: STIMULI_BIRD,
	[TYPE_RANDOMISED]: STIMULI_BIRD,
	[TYPE_NONRANDOMISED]: STIMULI_SNAKE
};