export const TRIAL_FEEDBACK = 'TRIAL_FEEDBACK';
export const TRIAL_ITI = 'TRIAL_ITI';
export const TRIAL_STIMULUS = 'TRIAL_STIMULUS';

export const TRIAL_FLOW = [
	TRIAL_ITI,
	TRIAL_STIMULUS,
	TRIAL_FEEDBACK,
];

export const TRIAL_ACTION_PHOTO = 'TRIAL_ACTION_PHOTO';
export const TRIAL_ACTION_SKIP = 'TRIAL_ACTION_SKIP';
